# Generated by Django 5.0.6 on 2024-10-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mlbb_app", "0005_alter_mlbb_community_community_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreateTournament",
            fields=[
                ("tournament_id", models.AutoField(primary_key=True, serialize=False)),
                ("tournament_name", models.CharField(max_length=100)),
                ("tournament_description", models.CharField(max_length=100)),
                ("tournament_type", models.CharField(max_length=100)),
                (
                    "tournament_image",
                    models.ImageField(blank=True, null=True, upload_to="tournaments/"),
                ),
                ("Game", models.CharField(max_length=100)),
                ("max_no_participants", models.IntegerField()),
                ("tournament_stages", models.CharField(max_length=100)),
                ("tournament_format", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("registration_fee", models.IntegerField()),
            ],
            options={
                "db_table": "tournaments",
            },
        ),
        migrations.CreateModel(
            name="ParticipatingTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_squad",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Tournament.createtournament",
                    ),
                ),
            ],
            options={
                "db_table": "participating_team",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1_score", models.IntegerField(blank=True, null=True)),
                ("team2_score", models.IntegerField(blank=True, null=True)),
                ("match_date", models.DateField(blank=True, null=True)),
                ("match_round", models.IntegerField()),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team1",
                        to="Tournament.participatingteam",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team2",
                        to="Tournament.participatingteam",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="Tournament.participatingteam",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
            },
        ),
        migrations.CreateModel(
            name="Bracket",
            fields=[
                ("bracket_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("total_round_number", models.IntegerField(default=1)),
                (
                    "parent_bracket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Tournament.bracket",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        to="Tournament.createtournament",
                    ),
                ),
                ("matches", models.ManyToManyField(blank=True, to="Tournament.match")),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Tournament.participatingteam",
                    ),
                ),
            ],
        ),
    ]
