# Generated by Django 5.0.6 on 2024-09-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="mlbb_profile",
            fields=[
                (
                    "mlbb_player_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("mlbb_player_ign", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("Account_id", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "mlbb_profile",
            },
        ),
        migrations.CreateModel(
            name="mlbb_squad",
            fields=[
                ("squad_name", models.CharField(max_length=50)),
                ("squad_id", models.IntegerField(primary_key=True, serialize=False)),
                ("squad_tag", models.CharField(max_length=50)),
                (
                    "squad_logo",
                    models.ImageField(blank=True, null=True, upload_to="squad_logo"),
                ),
                ("squad_country", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "applications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="squad_applications",
                        to="mlbb_app.mlbb_profile",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "invites",
                    models.ManyToManyField(
                        related_name="squad_invites", to="mlbb_app.mlbb_profile"
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squad_leader",
                        to="mlbb_app.mlbb_profile",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="squad_members", to="mlbb_app.mlbb_profile"
                    ),
                ),
            ],
            options={
                "db_table": "mlbb_squads",
            },
        ),
        migrations.AddField(
            model_name="mlbb_profile",
            name="squad_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mlbb_app.mlbb_squad",
            ),
        ),
        migrations.CreateModel(
            name="mlbb_Squad_Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "squad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_squad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_profile",
                    ),
                ),
            ],
            options={
                "db_table": "squad_applications",
            },
        ),
        migrations.CreateModel(
            name="mlbb_Squad_Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "squad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_squad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_profile",
                    ),
                ),
            ],
            options={
                "db_table": "squad_invites",
            },
        ),
    ]
