# Generated by Django 5.0.6 on 2024-09-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlbb_app", "0001_initial"),
        ("player_Account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlbb_profile",
            name="Account_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="player_Account.account"
            ),
        ),
    ]
