# Generated by Django 5.0.6 on 2024-06-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlbb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameSquadInvite',
            new_name='mlbb_Squad_Invite',
        ),
    ]
