# Generated by Django 5.0.6 on 2024-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlbb_app", "0002_alter_mlbb_profile_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlbb_squad",
            name="tournament_won",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
