# Generated by Django 5.0.6 on 2024-09-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlbb_app", "0003_mlbb_squad_tournament_won"),
    ]

    operations = [
        migrations.CreateModel(
            name="mlbb_community",
            fields=[
                ("community_id", models.AutoField(primary_key=True, serialize=False)),
                ("community_tag", models.CharField(max_length=255, unique=True)),
                ("community_name", models.CharField(max_length=50)),
                ("community_description", models.TextField()),
                ("community_image", models.ImageField(upload_to="images/")),
                ("community_country", models.CharField(max_length=50)),
                (
                    "applicants",
                    models.ManyToManyField(
                        related_name="applicant_communities", to="mlbb_app.mlbb_squad"
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_leader",
                        to="mlbb_app.mlbb_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mlbb_Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_community",
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_squad",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mlbb_community",
            name="squads",
            field=models.ManyToManyField(
                through="mlbb_app.mlbb_Membership", to="mlbb_app.mlbb_squad"
            ),
        ),
    ]
