# Generated by Django 5.0.6 on 2024-06-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlbb_app', '0003_alter_mlbb_squad_squad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbb_squad',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, related_name='squad_applications', to='mlbb_app.mlbb_profile'),
        ),
        migrations.AlterField(
            model_name='mlbb_squad',
            name='members',
            field=models.ManyToManyField(null=True, related_name='squad_members', to='mlbb_app.mlbb_profile'),
        ),
    ]
