# Generated by Django 5.0.6 on 2024-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlbb_app', '0004_alter_mlbb_squad_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbb_squad',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='squad_applications', to='mlbb_app.mlbb_profile'),
        ),
        migrations.AlterField(
            model_name='mlbb_squad',
            name='members',
            field=models.ManyToManyField(related_name='squad_members', to='mlbb_app.mlbb_profile'),
        ),
    ]
