# Generated by Django 5.0.6 on 2024-09-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlbb_app", "0004_mlbb_community_mlbb_membership_mlbb_community_squads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlbb_community",
            name="community_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterModelTable(
            name="mlbb_community",
            table="mlbb_community",
        ),
        migrations.CreateModel(
            name="mlbb_community_Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "mlbb_community",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlbb_app.mlbb_squad",
                    ),
                ),
            ],
            options={
                "db_table": "community_applications",
            },
        ),
    ]
